### ISSUE TITLE
how to get living meme role

### ISSUE THREAD

**Issue by Supergames699** [z64/kekbot#19]
i cant find living meme role pls help me

**Comment by z64** [comment]
Hi. I'm sorry, I'm afraid I don't know what you're talking about. 

If your question is about the "official" bot - it's currently offline ; I don't have time to work on it at the moment. 

If you are hosting the bot yourself I will need more details about your issue.

**Comment by Kryptonymous** [comment]
You don't have to "find" the living meme role, you must create a role with that name then assign that role to the bot itself.

**Comment by z64** [comment]
This issue, lmao.

**Comment by KristupasSavickas** [comment]
A living meme, one might say.
